version: "4.12"


services:

  fastapi:
    build: .
    command: [
      "uvicorn",
      "main:app",
      "--host=0.0.0.0",
      "--port=8000"
    ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"


